name: feature_discovery
description: >-
  A Flutter package that implements Material Design Feature discovery
  to show a description of specific features to new users.
  See https://material.io/archive/guidelines/growth-communications/feature-discovery.html
version: 0.5.1
authors: 
  - ayalma <alimohammadi7117@gmail.com>
  - creativecreatorormaybenot
  - axel-op
homepage: https://github.com/ayalma/feature_discovery

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
