name: feature_discovery
description: >-
  A Flutter package that implements Material Design Feature discovery
  to show a description of specific features to new users.
  See https://tinyurl.com/FeatureDiscovery
version: 0.6.0
homepage: https://github.com/ayalma/feature_discovery

environment:
  sdk: '>=2.2.2 <3.0.0' # This should never be higher than the Flutter stable constraints.

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0

dev_dependencies:
  pedantic: any
  flutter_test:
    sdk: flutter
