name: feature_discovery
description: A Flutter package that implements Material Design feature discovery to show a description of UI elements to the user.
version: 0.5.0
author: ayalma <alimohammadi7117@gmail.com>
homepage: https://github.com/ayalma/feature_discovery

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter