name: Flutter Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
      - run: flutter analyze

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
      - name: Check Dart Formatting
        run: flutter format --set-exit-if-changed -n .

  package-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
      - name: Install pana
        run: flutter pub global activate pana
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: ^3.7.4
      - name: Install PyGithub package
        run: pip install PyGithub
      - name: Run pana, process the output, and post comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: python ./.github/workflows/pana_scores.py $(pwd)
